- Changelog.md
- INSTALL_WINDOWS.md
- README.md
- bitbucket-pipelines.yml
- doc/header.html
- src/Zip_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [ign-fuel-tools1] Update BitBucket links

- CONTRIBUTING.md
- Changelog.md
- INSTALL_WINDOWS.md
- Migration.md
- README.md
- bitbucket-pipelines.yml
- doc/header.html
- src/ModelIter.cc
- src/Zip_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [ign-fuel-tools2] Update BitBucket links

- CONTRIBUTING.md
- Changelog.md
- INSTALL_WINDOWS.md
- Migration.md
- README.md
- bitbucket-pipelines.yml
- doc/header.html
- src/ModelIter.cc
- src/Zip_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [master] Update BitBucket links

- configure.bat
Instead of the default branch.
Signed-off-by: Steven Peters <scpeters@openrobotics.org>
> configure.bat: use ign-msgs master

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [ign-fuel-tools3] Workflow updates

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [ign-fuel-tools4] Workflow updates

- README.md
- example/details.cc
- example/download.cc
- include/ignition/fuel_tools/FuelClient.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/cmd/cmdfuel.rb.in
- src/ign_src_TEST.cc
- tutorials/03_command_line.md
The `openrobotics` user on Fuel was changed to the `OpenRobotics` organization.
> Openrobotics org name

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/ci-bionic/dependencies.yaml
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- .gitignore
- Changelog.md
- README.md
- codecov.yml
- configure.bat
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface.cc
- src/Interface_TEST.cc
- src/ModelIter.cc
- src/RestClient.cc
- src/cmd/cmdfuel.rb.in
Includes #72 
Also modified the actions CI to build `ign-msgs6` from source.
> 4 ➡️ master

- tools/code_check.sh
- tools/cpplint.py
This should fix the code check error reported in https://build.osrfoundation.org/job/ignition_fuel-tools-ci-ign-fuel-tools4-bionic-amd64/19/.
I copied cpplint.py from ign-gazebo and only make changes to `code_check.sh` to use updated command line arguments.
> Update cpplint to fix code check error

- BUILD.bazel
- src/Interface_TEST.cc
- test/BUILD.bazel
- test/test_util.hh
Signed-off-by: John Shepherd <john@openrobotics.org>
> [Bazel] Init attempt at bazel build files

- BUILD.bazel
Signed-off-by: John Shepherd <john@openrobotics.org>
> Add ign export headers

- README.md
- example/details.cc
- example/download.cc
- include/ignition/fuel_tools/FuelClient.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/cmd/cmdfuel.rb.in
- src/ign_src_TEST.cc
- tutorials/03_command_line.md
> Merge 3 to 4, July 14 2020

- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
Now that the action can actually fail, I realized it's missing a dependency.
> Add missing dep in Actions CI

- CMakeLists.txt
- Changelog.md
> 3.4.0 prep

- README.md
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
- tutorials/index.md
Updated documentation links and other minor fixes
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>
> Updated documentation links and other minor fixes

- CMakeLists.txt
- Changelog.md
> Preparing for 5.0.0 release

- src/FuelClient.cc
Downloads the dependencies listed in a `model.config` file, depends on https://github.com/ignitionrobotics/ign-msgs/pull/91
Signed-off-by: John Shepherd <john@openrobotics.org>
> Add support for model config dependencies

- src/ign.cc
This PR is meant to resolve new codecheck issues introduced by https://github.com/ignitionrobotics/ign-cmake/pull/117.
From my understanding, the plan is to forward port the fixes here to all other ignition versions once https://github.com/ignitionrobotics/ign-cmake/pull/117 is merged.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
> Resolve updated codecheck issues

- CMakeLists.txt
- Changelog.md
Waiting on #143 
[Changes](https://github.com/ignitionrobotics/ign-fuel-tools/compare/ignition-fuel-tools5_5.0.0...ign-fuel-tools5).
> Prepare for 5.1.0 release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/port.md
Related to ignitionrobotics/docs#138
Adds a template for opening new issues and pull requests
> added issue & PR templates

- CMakeLists.txt
- Changelog.md
Preparation for 6.0.0~pre1 release.
Comparison to version 5: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ign-fuel-tools5...main
> 🎈 6.0.0~pre1

- example/README.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Add some instructions about how to compile the example on Windows
> Include windows instructions in examples README.md

- Changelog.md
Preparation for 7.0.0~pre1 release.
Comparison to v6: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ign-fuel-tools6...main
https://github.com/ignition-tooling/release-tools/issues/459
> 🎈 7.0.0~pre1

- tutorials/01_installation.md
Added source macos install instructions
> Added source macos install instructions

- .github/ci/packages.apt
- CMakeLists.txt
- tutorials/01_installation.md
See https://github.com/ignition-tooling/release-tools/issues/554
> Bumps in garden : ci_matching_branch/bump_garden_ign-fuel-tools8

- Changelog.md
- include/ignition/fuel_tools/FuelClient.hh
- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier_TEST.cc
- src/cmd/CMakeLists.txt
- src/ign.cc
- src/ign_src_TEST.cc
Port ign-fuel-tools7 as of https://github.com/ignitionrobotics/ign-fuel-tools/commit/2c29dd7ae024bfedb03bf50313ed56524fb8e8fb to main
Substitute for #240 while we wait for ign-msgs9 debs on jammy
Branch comparison: https://github.com/ignitionrobotics/ign-fuel-tools/compare/main...2c29dd7ae024bfedb03bf50313ed56524fb8e8fb
> Merge part of 7 -> main

- .github/workflows/ci.yml
- include/ignition/fuel_tools/Interface.hh
- src/Interface.cc
- src/Interface_TEST.cc
Port ign-fuel-tools7 to main
Branch comparison: https://github.com/ignitionrobotics/ign-fuel-tools/compare/main...ign-fuel-tools7
> Merge 7 -> main

- .github/ci/packages.apt
- CMakeLists.txt
- configure.bat
- src/CMakeLists.txt
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/LocalCache_TEST.cc
- src/ign_TEST.cc
- src/ign_src_TEST.cc
- tutorials/01_installation.md
See https://github.com/ignition-tooling/release-tools/issues/685
> Bumps in garden : ign-fuel-tools8

- Changelog.md
- src/Zip.cc
Port `ign-fuel-tools7 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-fuel-tools/compare/main...ign-fuel-tools7
> Merge ign-fuel-tools7 ➡️  main

- Changelog.md
- include/ignition/fuel_tools/Interface.hh
- src/ign_TEST.cc
- src/ign_src_TEST.cc
Port `ign-fuel-tools4 ` ➡️  `ign-fuel-tools7`
Branch comparision: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ign-fuel-tools7...ign-fuel-tools4
> Merge ign-fuel-tools4 ➡️  ign-fuel-tools7

- .github/ci/after_make.sh
- Changelog.md
- INSTALL_WINDOWS.md
- Migration.md
- README.md
- api.md.in
- configure.bat
- example/README.md
- src/Helpers_TEST.cc
- src/LocalCache.cc
- tutorials.md.in
- tutorials/01_installation.md
- tutorials/03_command_line.md
See: https://github.com/gazebo-tooling/release-tools/issues/757
> ign -> gz Partial Docs Migration and Project Name Followups : gz-fuel-tools

- include/gz/fuel_tools/gz_auto_headers.hh.in
See: https://github.com/gazebo-tooling/release-tools/issues/767
> ign -> gz Provisional Finale: Source Migration : gz-fuel-tools

- README.md
See: https://github.com/gazebo-tooling/release-tools/issues/757
> ign -> gz Migrate config and log directories : gz-fuel-tools

- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier_TEST.cc
- src/ModelIter_TEST.cc
- src/RestClient.cc
- src/Result_TEST.cc
- src/WorldIdentifier_TEST.cc
- src/WorldIter.cc
- src/WorldIter_TEST.cc
- src/Zip.cc
- src/Zip_TEST.cc
- test/integration/zip.cc
Part of: https://github.com/gazebo-tooling/release-tools/issues/784
> ign -> gz : Remove redundant namespace references

- Migration.md
- include/gz/fuel_tools/ModelIdentifier.hh
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier_TEST.cc
Port gz-fuel-tools8 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools8
> 8 to main 20220816

- README.md
- src/cmd/cmdfuel.rb.in
Updates the help strings in the CLI to use `fuel.gazebosim.org`.
> Update cmd line tool help to use gazebosim

- tutorials/02_configuration.md
Updates text in the configuration tutorial.
> Update configuration instructions

- tutorials/03_command_line.md
- tutorials/04_cpp_api.md
> Update cli tutorial

- Changelog.md
Preparation for 8.0.0 release.
https://github.com/gazebosim/gz-fuel-tools/pulls?q=is%3Apr+is%3Aclosed+label%3A%22%F0%9F%8C%B1+garden%22
> 8 0 0 release

- tutorials/01_installation.md
Improved install instructions
Related with https://github.com/gazebosim/garden-tutorial-party/issues/2070
> Improved install instructions

- Changelog.md
- include/gz/fuel_tools/Interface.hh
- src/CMakeLists.txt
- src/FuelClient.cc
- src/RestClient.cc
- src/WorldIter.cc
- src/Zip.cc
- src/gz_src_TEST.cc
Port ign-fuel-tools7 to gz-fuel-tools8
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools8...ign-fuel-tools7
> port: 7 to 8 2022-11-16

- CMakeLists.txt
- Changelog.md
Preparation for 4.7.0 release.
Comparison to 4.6.0: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools4_4.6.0...ign-fuel-tools4
> 4.7.0 release

- CMakeLists.txt
- Changelog.md
Preparation for 7.2.0 release.
Comparison to 7.1.0: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools7_7.1.0...ign-fuel-tools7
> 7.2.0 release

- CMakeLists.txt
- Changelog.md
- README.md
- include/gz/fuel_tools/Interface.hh
- src/CMakeLists.txt
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface.cc
- src/Interface_TEST.cc
- src/RestClient.cc
- src/WorldIter.cc
- src/Zip.cc
- src/cmd/cmdfuel.rb.in
- src/gz.cc
- src/gz_TEST.cc
- src/gz_src_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/03_command_line.md
- tutorials/04_cpp_api.md
Port gz-fuel-tools8 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools8
> port: 8 to main 2022-11-17

- CMakeLists.txt
- Changelog.md
Preparation for 4.8.1 release.
Comparison to 4.8.0: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ignition-fuel-tools4_4.8.0...ign-fuel-tools4
Needed by <PR(s)>
> Prepare for 4.8.1 Release

- CMakeLists.txt
- Changelog.md
Preparation for 4.8.2 release.
Comparison to 4.8.1: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools4_4.8.1...ign-fuel-tools4
> 4.8.2 release

- CMakeLists.txt
- Changelog.md
Preparation for 7.2.1 release.
Comparison to 7.2.0: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools7_7.2.0...ign-fuel-tools7
> 7.2.1 release

- CMakeLists.txt
- Changelog.md
Preparation for 7.2.2 release.
Comparison to 7.2.1: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools7_7.2.1...ign-fuel-tools7
> 7.2.2 release

- Changelog.md
- src/FuelClient.cc
- src/RestClient.cc
Port ign-fuel-tools7 to gz-fuel-tools8
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools8...ign-fuel-tools7
> Forward port 7 to 8

- CMakeLists.txt
- Changelog.md
Preparation for 4.9.0 release.
Comparison to 4.8.3: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools4_4.8.3...ign-fuel-tools4
Needed by https://github.com/gazebosim/gz-sim/pull/1962
- ~[ ] Updated migration guide (as needed)~
> Prepare for 4.9.0 Release

- src/LocalCache_TEST.cc
Port `gz-fuel-tools8 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools8
> Merge gz-fuel-tools8 ➡️  main

- src/ClientConfig.cc
- src/FuelClient.cc
- src/Interface.cc
- src/Model.cc
- src/ModelIdentifier.cc
- src/Model_TEST.cc
- src/WorldIdentifier.cc
- Replace ign log macros with gz
- Clangtidy fixes
> Minor cleanup

- CMakeLists.txt
- Changelog.md
Preparation for 9.0.0~pre2 release.
Comparison to 8.1.0: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools8_8.1.0...gz-fuel-tools9
> Update changelogs and Prepare for 9.0.0~pre2 Release

- CMakeLists.txt
- Changelog.md
Preparation for 9.0.0 release.
Comparison to 9.0.0-pre2: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools9_9.0.0-pre2...gz-fuel-tools9
Needed by <PR(s)>
> Prepare for 9.0.0 Release

- .github/ci/packages.apt
- CMakeLists.txt
- tutorials/01_installation.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1027
> Bumps in ionic : ci_matching_branch/bump_ionic_gz-fuel-tools10

- CMakeLists.txt
- Changelog.md
Preparation for 7.3.1 release.
Comparison to 7.3.0: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools7_7.3.0...ign-fuel-tools7
> Prepare for 7.3.1 Release

- src/CollectionIdentifier.cc
- src/WorldIdentifier.cc
Port gz-fuel-tools9 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools9
> Merge 9 -> main

- README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
> Update badges to point to gz-fuel-tools10

- CMakeLists.txt
Preparation for gz-fuel-tools10.0.0~pre2 release.
Comparison to gz-fuel-tools10.0.0~pre1: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools10_10.0.0-pre1...prep_10.0.0pre2
> Prepare for gz-fuel-tools10.0.0~pre2 release

- CMakeLists.txt
- Changelog.md
Preparation for 4.9.2 release.
Comparison to 4.9.1: https://github.com/azeey/gz-fuel-tools/compare/ignition-fuel-tools4_4.9.1...ign-fuel-tools4
Part of https://github.com/gazebo-tooling/release-tools/issues/1252
> Prepare for 4.9.2 Release

- .github/workflows/ci.yml
- Changelog.md
- example/download.cc
- include/gz/fuel_tools/Helpers.hh
- include/gz/fuel_tools/Model.hh
- include/gz/fuel_tools/ModelIdentifier.hh
- include/gz/fuel_tools/WorldIdentifier.hh
- src/gz.cc
Port gz-fuel-tools10 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools10
> Merge 10 -> main

- .github/ci/packages.apt
- .github/workflows/ci.yml
- CMakeLists.txt
- example/CMakeLists.txt
- package.xml
- src/CMakeLists.txt
- test/integration/CMakeLists.txt
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
> Bump gz-cmake and others in jetty

- .github/workflows/bazel.yml
- MODULE.bazel
Change `main` to jetty release branches
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> [Bazel] Update bazel module to use jetty release branches
