- CONTRIBUTING.md
- Changelog.md
- INSTALL_WINDOWS.md
- Migration.md
- README.md
- bitbucket-pipelines.yml
- doc/header.html
- src/ModelIter.cc
- src/Zip_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [ign-fuel-tools3] Update BitBucket links

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [ign-fuel-tools1] Workflow updates

- Changelog.md
- src/cmd/cmdfuel.rb.in
This just re-orders the subcommands to be alphabetical.
> Alphabetical listing of subcommands

- CONTRIBUTING.md
- Changelog.md
- INSTALL_WINDOWS.md
- Migration.md
- README.md
- bitbucket-pipelines.yml
- configure.bat
- doc/header.html
- src/ModelIter.cc
- src/Zip_TEST.cc
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
I had forgot about this branch when updating links.
:farmer:  Also included some changes to try and fix the Windows CI:
https://build.osrfoundation.org/job/ignition_fuel-tools-ci-ign-fuel-tools4-windows7-amd64/
> [ign-fuel-tools4] Update BitBucket links

- CMakeLists.txt
- Changelog.md
- src/RestClient.cc
The "Drag Me" feature on Fuel is broken for models with spaces in the name. The root problem is that we are encoding URLs that were already encoded.
This change first decodes a URL, replacing "%XX" characters with their ASCII equivalent. This allows encoding to proceed correctly.
We are preventing resources from containing percent signs in:
1. https://gitlab.com/ignitionrobotics/web/fuelserver/-/merge_requests/15
2. https://gitlab.com/ignitionrobotics/web/app/-/merge_requests/17
> Fix URL path encoding

- src/FuelClient_TEST.cc
- src/ign_src_TEST.cc
I think some worlds were removed from the server and this caused the tests to fail.
I also reduced a bit the reliance on the staging server.
> Fix world tests

- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/ign_src_TEST.cc
I uploaded new versions of the test worlds so that they now have both `.world` (deprecated) and `.sdf` files. And having a new world version made a bunch of tests fail.
It's unfortunate that the tests need to be updated whenever the worlds are changed, but the hope is that this isn't something we'll do very often :crossed_fingers:
> Fix test worlds

- README.md
- tutorials/01_installation.md
This PR is related with this issue https://github.com/ignitionrobotics/docs/issues/14
Moved install instructions to the tutorials folder.
> Removed repeated installation instructions

- include/ignition/fuel_tools/Result.hh
- src/CollectionIdentifier_TEST.cc
- src/Result.cc
- src/Result_TEST.cc
The Windows build was broken on #98.
The problem was using a class that doesn't have a default constructor inside a future:
https://github.com/ignitionrobotics/ign-fuel-tools/blob/2eb0ee784c0c795289dd34e64ff2b814f9cc64c8/src/ign.cc#L611
I tried a few different things but ended up just giving the class a default constructor, which I don't think is unreasonable.
> 👩‍🌾 Fix Windows build

- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/ign_src_TEST.cc
Fixed 
- UNIT_FuelClient_TEST
- UNIT_ign_src_TEST
- UNIT_Interface_TEST
> Fixed test - Download world 2

- CMakeLists.txt
- Changelog.md
We need a new release in order to support model download for SubT + Citadel docker images.
> 4.2.0 prep

- CMakeLists.txt
- Changelog.md
- src/cmd/cmdfuel.rb.in
I missed [this error](https://github.com/ignitionrobotics/ign-fuel-tools/pull/102/files#diff-e2cbfe78be4b938d0d98f934858418dfL144) when merging forward.
The `-j and -t` options should be associated with `download`, not `upload`.
> Missing download j option

- CMakeLists.txt
- example/CMakeLists.txt
The `ign-fuel-tools5` branch was created off main for the Dome release.
Now bumping main to version 6 so it may receive breaking changes.
> ⬆️ Bump main to 6.0.0~pre1

- src/ign_src_TEST.cc
Similar to https://github.com/ignitionrobotics/ign-gazebo/pull/455
This is not the best long-term fix, but it will make the builds green again.
> Update Backpack model to fix tests

- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
- src/ign_src_TEST.cc
This will store models and worlds using lowercase name and owner. 
I've done the following tests:
1. Run SubT worlds with an existing cache that has capitalization. Result: nothing new is downloaded, and the worlds run.
2. Run SubT world with some models missing from the cache. Result: new models are downloaded to all lowercase directories.
3. Run worlds with random capitalization in model URIs. Result: utilizes existing cache, or downloads new resources.
4. Download a collection, such as `ign fuel download -v 4 -j 8 -u "https://fuel.ignitionrobotics.org/OpenRobotics/collections/SubT Tech Repo"`. Result: This will download all the models using lowercase.
5. If there is a model is two places, such as `OpenRobotics/models/X1 Config 1` and `openrobotics/x1 config 1`, then the lower case …
> Use lowercase resource and owner names when storing assets on disk

- CMakeLists.txt
- Changelog.md
> Prepare for 3.5.0 release

- CMakeLists.txt
- Changelog.md
> Prepare for 4.3.0 release

- src/RestClient.cc
This adds keepalive options to curl. The command line version of curl has this enabled by default, and I've found that these parameters help downloading large models and collections.
Reference: https://curl.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html
Reference: https://ec.haxx.se/usingcurl/usingcurl-timeouts#:~:text=By%20using%20keep%2Dalive%2C%20curl,default%20value%20is%2060%20seconds.
> Set keep alive on

- Changelog.md
- include/ignition/fuel_tools/FuelClient.hh
- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/RestClient.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
- src/cmd/cmdfuel.rb.in
- src/ign.cc
- src/ign.hh
- src/ign_src_TEST.cc
> 4 to 5 11302020

- src/LocalCache.cc
so we can convert `model://<model_name>/<path_to_texture>.png` to absolute path on local disk.
related pull request: ignitionrobotics/ign-gazebo#471
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
> Fix light map URI in materials

- src/cmd/cmdfuel.rb.in
I always forget what the exact environment variable is. I think we should start documenting all variables on the command line, like `ign-gazebo` does.
> Document IGN_FUEL_CACHE_PATH on command line

- .github/ci/packages.apt
- CMakeLists.txt
- src/LocalCache.cc
I was getting a crash while downloading a model with a malformed config:
```
$ ign fuel download -j 4 -v 4 -u "https://fuel.ignitionrobotics.org/1.0/openrobotics/models/Universal Robotics UR10 robot arm"
...
terminate called after throwing an instance of 'std::logic_error'                                                                           
what():  basic_string::_M_construct null not valid                     
Aborted (core dumped)   
```
The problem is that the `<sdf>` element of that model doesn't have a `version` attribute.
To prevent a crash, I'm assuming a version 0.0.1.
Which begs the question, is that version meant to be semantic? I don't think that has been specified anywhere. But considering that most models have a version in the format `X.X`, I think semantic versioning …
> Use semantic version and prevent crash if version is missing

- .github/ci/packages.apt
- CMakeLists.txt
- configure.bat
- include/ignition/fuel_tools/FuelClient.hh
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Part of https://github.com/ignition-tooling/release-tools/issues/362.
The script also updated some `ign-fuel-tools5` that was left in the `main` branch.
Supersedes https://github.com/ignitionrobotics/ign-fuel-tools/pull/152/
> Bump in edifice: ign-msgs7

- Migration.md
- include/ignition/fuel_tools/FuelClient.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
Deprecated `FuelClient::DeleteModel`.
`LocalCache` is deprecated in v5, but it can't be removed in v6 because it's used in a public constructor of `FuelClient`. So I deprecated that constructor and we can only move `LocalCache` to `src` in v7.
> Edifice deprecations

- README.md
- tutorials/01_installation.md
A retarget of https://github.com/ignitionrobotics/ign-fuel-tools/pull/154 to Citadel
> Add Windows Installation

- include/ignition/fuel_tools/ClientConfig.hh
- include/ignition/fuel_tools/FuelClient.hh
- src/ClientConfig.cc
- src/FuelClient.cc
- tutorials/02_configuration.md
- tutorials/03_command_line.md
Related with this issue: https://github.com/ignitionrobotics/ign-fuel-tools/issues/155
Included a new field called `private-token` to allow the identification with the server using the yaml file.
> Included private-token to config.yaml

- CMakeLists.txt
- Changelog.md
- example/CMakeLists.txt
- tutorials/01_installation.md
- tutorials/02_configuration.md
- tutorials/04_cpp_api.md
Branch `ign-fuel-tools6` has been created for the Edifice release and 6.0.0 released from that.
The `main` branch now corresponds to version 7.0.0~pre1, and nightlies will soon be created from this branch.
https://github.com/ignition-tooling/release-tools/issues/421
> Bump main to 7.0.0~pre1

- .github/ci/packages.apt
- CMakeLists.txt
- tutorials/01_installation.md
See https://github.com/ignition-tooling/release-tools/issues/428
> Bumps in fortress : ign-fuel-tools7

- src/ClientConfig_TEST.cc
- src/CollectionIdentifier.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface.cc
- src/Interface_TEST.cc
- src/LocalCache.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/ModelIter.cc
- src/WorldIdentifier_TEST.cc
- src/WorldIter.cc
- src/Zip.cc
- src/ign_src_TEST.cc
This PR will allow to download model and world on Windows. I checked the functionality with the executable `download` in the example folder.
Should I retarget this a different ign-fuel-tools version ?
> Fixed windows download

- include/ignition/fuel_tools/FuelClient.hh
- include/ignition/fuel_tools/WorldIter.hh
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier_TEST.cc
- src/WorldIter.cc
- src/cmd/cmdfuel.rb.in
- src/ign.cc
- src/ign.hh
Signed-off-by: Tomas Lorente <jtlorente@ekumenlabs.com>
Update command for fuel
`ign fuel update`, supports --onlymodels and --onlyworlds to select if you only want to download one of those. By default downloads both.
Download a model or a world, modify that one in fuel to up the version, call the command and see it update.
> added fuel update command

- CMakeLists.txt
Part of https://github.com/ignition-tooling/release-tools/issues/472
I don't detect the conditional installation of the `ign` submodule, the PR just
changed the way of detecting ign for testing.
> Detect ign instead of using cmake module to check for ignition-tools

- CMakeLists.txt
The error message users get when curl is missing from the system is that `IgnCURL` is missing, which can be confusing.
> Use a pretty name for IgnCURL to make error messages less confusing

- include/ignition/fuel_tools/FuelClient.hh
- src/ClientConfig_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/ign.cc
Closes #188 
Adds APIs for downloading a set of models in parallel.
> APIs for retrieving models in parallel

- src/FuelClient.cc
- src/ign.cc
- src/ign_src_TEST.cc
Fixes the Windows build.
The `std::deque` datatype was used in #199, but the Windows compiler seems to have trouble identifying the datatype. Seems like a missing header.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_fuel-tools-ign-4-win&build=8)](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/8/) https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/8/
> FuelClient.cc: include <deque>

- src/cmd/CMakeLists.txt
Fix cmdfuel ruby script generation on Windows with MSVC
Before this script, when running commands like `ign fuel download` on Windows failed with:
~~~
(igngazebo) C:\Users\STraversaro>ign fuel download -v --url https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/Ambulance
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
Library error: [libignition-fuel_tools7.so] not found.
~~~
After this fix:
~~~
(igngazebo) C:\Users\STraversaro>ign fuel download -v --url https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/Ambulance
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
Library error: [libignition-fuel_tools7.so] not found.
~~~
**Note to maintainers**: Remember to use …
> Fix cmdfuel ruby script generation on Windows with MSVC

- .github/ci/packages.apt
- CMakeLists.txt
- src/ClientConfig_TEST.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient_TEST.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier_TEST.cc
- tutorials/01_installation.md
See https://github.com/ignition-tooling/release-tools/issues/574
> Bumps in garden: use ign-common5

- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
While debugging test failures on #224, I noticed that some of our `ResultType` tests were comparing `Result` objects converted to booleans instead of the result types themselves. This PR makes sure we're comparing the types and fixes some test expectations.
> Improve and fix ResultType tests

- src/ign_src_TEST.cc
While debugging a test failure, I noticed that the tests in `ign_src_TEST` would fail if run from outside the build directory. So I fixed this by passing `PROJECT_BINARY_PATH` to all the places where the `test_cache` is accessed. In order to reduce duplication, I moved that logic to the `SetUp` function. While at it, I reduced more duplication by moving the `IO` functions to `SetUp` / `TearDown`.
The fix can be checked by running the test from a directory other than `build`, for example:
`./build/ignition-fuel_tools5/bin/UNIT_ign_src_TEST`
> Move test cache to build folder

- src/ClientConfig_TEST.cc
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/LocalCache_TEST.cc
- src/ign_src_TEST.cc
These checks are useful when debugging test failures. At a minimum, they allow us to rule-out these lines are reasons for the failure.
The changes consist in expecting true for these calls:
* `createDirectories`
* `copyFile`
This is motivated by debugging #224 
CI should pass for all platforms
> More checks when manipulating file system in tests

- include/ignition/fuel_tools/FuelClient.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/LocalCache.cc
- src/LocalCache.hh
- src/LocalCache_TEST.cc
This includes moving LocalCache.hh from public headers as a follow up to #109
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Remove deprecated functions from fuel_tools8

- src/Zip.cc
While reviewing https://github.com/ignitionrobotics/ign-gazebo/pull/1262, some files were failing to download, but I was getting success messages. This PR just makes sure that a success message isn't printed on failure.
Before this PR we get false positives:
```
$ ign fuel download -v 4 --url "https://fuel.ignitionrobotics.org/1.0/jennuine/models/Monterey Bay"          
Downloading model:                                                                                                                          
Name: monterey bay                                                                                                                          Owner: jennuine …
```
> Print error when unzipping fails to save a file

- src/ClientConfig_TEST.cc
- src/LocalCache_TEST.cc
Fix tests that have been failing since https://github.com/ignitionrobotics/ign-common/pull/275 was merged
From https://github.com/ignitionrobotics/ign-common/pull/275:
> The issue is that the URIPath::Implementation struct has a trailingSlash member:  https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI.cc#L54-L73
> The originally written copy-assignment operator doesn't copy this member:
https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI.cc#L586-L591
> And the test exercises this copy-assignment:
https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI_TEST.cc#L890-L894
> In this case, ImplPtr has shown that the previous behavior is actually a bug, and we should fix it in previous versions.
So there was a bug in handling of trailing …
> Fix trailing slash expectations in failing tests

- .github/workflows/ci.yml
Part of https://github.com/ignition-tooling/release-tools/issues/566
Enable CI for Ubuntu 22.04 (Jammy)
>  Add Ubuntu Jammy CI

- .github/workflows/ci.yml
- README.md
* See https://github.com/ignition-tooling/release-tools/issues/597
`ign-fuel-tools8` will be on Garden.
No Bionic builds should be triggered.
> Remove Bionic from future releases (Garden+)

- include/ignition/fuel_tools/Result.hh
- src/ClientConfig_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface_TEST.cc
- src/LocalCache_TEST.cc
- src/RestClient.cc
- src/RestClient_TEST.cc
- src/ign_TEST.cc
- src/ign_src_TEST.cc
- test/CMakeLists.txt
- test/integration/zip.cc
This moves the generated `test_config.h` to not be in `test`, which brings it in line with the rest of the ignition packages.
It also rearranges a bit of the gtest cmake logic so that the targets/includes are more explicit.
> Move test_config to align with other packages

- include/ignition/fuel_tools/Interface.hh
Noticed it was missing during #248 
> Add missing header guard for Interface.hh

- src/ign_TEST.cc
- src/ign_src_TEST.cc
Disables tests being caused by https://github.com/gazebosim/gz-fuel-tools/issues/254.
> Disable staging-fuel.ignitionrobotics.org test

- CMakeLists.txt
- conf/CMakeLists.txt
- conf/fuel.yaml.in
- include/gz/fuel_tools/CMakeLists.txt
- src/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/performance/CMakeLists.txt
- test/regression/CMakeLists.txt
* Part of https://github.com/gazebo-tooling/release-tools/issues/719
> [ign -> gz] CMake functions

- Migration.md
- README.md
- conf/fuel.yaml.in
- include/gz/fuel_tools/ClientConfig.hh
- include/gz/fuel_tools/FuelClient.hh
- include/gz/fuel_tools/Helpers.hh
- include/gz/fuel_tools/Interface.hh
- include/ignition/fuel_tools/Helpers.hh
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/FuelClient_TEST.cc
- src/cmd/cmdfuel.rb.in
- src/ign.cc
- src/ign.hh
- src/ign_TEST.cc
- test/test_config.h.in
See: https://github.com/gazebo-tooling/release-tools/issues/737
> ign -> gz Macro Migration : gz-fuel-tools

- tutorials/04_cpp_api.md
Fixed cpp api tutorial links. https://github.com/gazebosim/garden-tutorial-party/issues/2050
> Fixed cpp api tutorial links

- tutorials/02_configuration.md
Fixed configuration tutorial links and some other tweaks. Related with https://github.com/gazebosim/garden-tutorial-party/issues/2068
> Fixed configuration tutorial links

- example/CMakeLists.txt
- src/FuelClient.cc
- src/Interface.cc
- src/gz.cc
Related to: https://github.com/gazebosim/gz-sim/pull/1771
Remove some Windows warnings.
> Clean up a few Windows warnings

- src/FuelClient_TEST.cc
This helps to fix #315 by using models that have been reduced in size. The changed models had their images and meshes removed, and move to the `openroboticstest` account on Fuel.
> Reduce asset download sizes in Fuel_Client_TEST

- src/gz_src_TEST.cc
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
Fixes https://github.com/gazebosim/gz-fuel-tools/issues/315#issuecomment-1344362711
As Ian said in https://github.com/gazebosim/gz-sim/pull/1853. "The [backpack](https://app.gazebosim.org/OpenRoboticsTest/fuel/models/Backpack) model was updated in December", so these test are failing because the version that they expect is incorrect.
> Change backpack model version 2->3

- Changelog.md
- src/gz_src_TEST.cc
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
Port ign-fuel-tools7 to gz-fuel-tools8
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools8...ign-fuel-tools7 
> This PR applies https://github.com/gazebosim/gz-fuel-tools/pull/319 to gz-fuel-tools8
> port: 7 to 8 2023-01-25

- Migration.md
- src/CMakeLists.txt
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/FuelClient_TEST.cc
Might fix: https://github.com/gazebosim/gazebo-classic/issues/3288
Fixes problem mentioned in: https://answers.gazebosim.org/question/28699/ignition-gazebo-citadel-can-no-longer-load-worlds-from-fuelgazebosimorg/
The FuelClient library was only looking for models in `~/.ignition/fuel/fuel.gazebosim.org` regardless of which server models were downloaded from when checking if a model is cached. This caused models that used the deprecated `ignitionrobotics.org` URI to be redownloaded every time. This PR fixes it by adding `ignitionrobotics.org` as an additional server to check.
It also seems like when a cache isn't found, the file path returned uses the `tip` leaf directory instead of the actual version number. Since the `tip` directory never exists, gazebo fails with a file not found error. …
> Fix model downloads for ignitionrobotics.org URIs

- .github/ci/packages.apt
- CMakeLists.txt
- tutorials/01_installation.md
Signed-off-by: Ian Chen <ichen@openrobotics.org>
Now that msgs and transport are recently bumped (to msgs10 and transport13) in harmonic, we need to bump all packages that depend on them. In this case, harmonic should now use fuel-tools9. 
I noticed that the package dependency versions were bumped in `main` in https://github.com/gazebosim/gz-fuel-tools/commit/83077ca167f2b24cf8bd23f7c016c36db5f68b1b. Here I'm just updating all of them to correspond to the correct gz package versions that we currently use in harmonic
Related PR: 
* https://github.com/gazebo-tooling/gazebodistro/pull/131
* https://github.com/gazebo-tooling/release-tools/pull/876
* https://github.com/osrf/homebrew-simulation/pull/2203
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to …
> Update package deps for harmonic

- src/RestClient.cc
Retargeting #330 to Citadel. See #330 for more information about redirects.
I'm scoping this change to only GET requests.
Try running the following command. The Staging Fuel server is setup to redirect requests to S3.
```
ign fuel download -u https://staging-fuel.gazebosim.org/1.0/marcoshuck5/models/testcoro
```
> Allow Curl redirect on get

- Changelog.md
This is just a changelog, so I'll go ahead and merge this asap.
Port ign-fuel-tools4 to ign-fuel-tools7
Branch comparison: [https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>](https://github.com/gazebosim/gz-fuel-tools/compare/ign-fuel-tools7...ign-fuel-tools4)
> Forward port 4 to 7 (Just changelog)

- src/LocalCache_TEST.cc
Fixes #307 (Partially)
This PR disables LocalCache Tests for Windows
> Disable all LocalCache Tests for Windows

- include/gz/fuel_tools/FuelClient.hh
- include/gz/fuel_tools/ModelIterPrivate.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/ModelIter.cc
Toward https://github.com/gazebosim/gz-sim/issues/1253
The `ModelIter` iterator was fetching all available pages before making the first model available. This PR makes it so that each page is fetched from Fuel when the iterator is advanced.
This also adds a new member function `FuelClient::Models(onst ModelIdentifier &_id, bool _checkCache)` that allows bypassing the cache when getting a list of models owned by a user from the server. i.e, Currently, we do the following to get a list of models for a user
```c++
FuelClient client();
ModelIdentifier modelId;
modelId.SetOwner("openroboticstest");
for (ModelIter iter = client.Models(modelId); iter; ++iter)
{ ... }
```
However, if there's even a single model from that owner already downloaded into the cache, `FuelClient::Models` will return …
> Reflect pagination of RESTful requests in iterator API 

- CMakeLists.txt
- Changelog.md
Preparation for 7.3.0 release.
Comparison to 7.2.2: https://github.com/gazebosim/gz-fuel-tools/compare/ignition-fuel-tools7_7.2.2...ign-fuel-tools7
Needed by https://github.com/gazebosim/gz-sim/pull/2013
> 7.3.0 Release

- include/gz/fuel_tools/config.hh.in
Fixes part of https://github.com/gazebosim/gz-sim/issues/626
As described in https://github.com/gazebosim/gz-sim/issues/626, we are getting rid of non-relocatable macros. On other libraries this macros have been replaced with functions, but in this case the macro seems unused, so we can simply deprecate it and remove it in a future gz-fuel-tools release. If necessary, relocatable functions can be added in the future.
> Deprecated non-relocatable macro

- src/Zip.cc
Port `ign-fuel-tools4 ` ➡️  `ign-fuel-tools7`
Branch comparison: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ign-fuel-tools7...ign-fuel-tools4
> Merge ign-fuel-tools4 ➡️  ign-fuel-tools7

- CMakeLists.txt
- Changelog.md
- include/gz/fuel_tools/FuelClient.hh
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/ModelIter.cc
- src/ModelIterPrivate.hh
- src/Zip.cc
- src/cmd/CMakeLists.txt
- src/cmd/cmdfuel.rb.in
- src/cmd/fuel.bash_completion.sh
Port `ign-fuel-tools7 ` ➡️  `gz-fuel-tools8`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools8...ign-fuel-tools7
> Merge ign-fuel-tools7 ➡️  gz-fuel-tools8

- BUILD.bazel
- CMakeLists.txt
- Changelog.md
- Migration.md
- include/gz/fuel_tools/FuelClient.hh
- include/gz/fuel_tools/config.hh.in
- src/CMakeLists.txt
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Interface.cc
- src/Interface_TEST.cc
- src/LocalCache_TEST.cc
- src/Model.cc
- src/ModelIdentifier.cc
- src/ModelIter.cc
- src/ModelIterPrivate.hh
- src/Model_TEST.cc
- src/RestClient_TEST.cc
- src/WorldIdentifier.cc
- src/Zip.cc
- src/cmd/CMakeLists.txt
- src/cmd/cmdfuel.rb.in
- src/cmd/fuel.bash_completion.sh
- test/BUILD.bazel
Port `gz-fuel-tools8 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools8
> Merge gz-fuel-tools8 ➡️  main

- .github/workflows/ci.yml
`harmonic` drops support for `focal`
> Drop focal from fuel_tools9 forward

- tutorials/01_installation.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/546
> Modifies the use of ign for gz in installation tutorial

- tools/gz-update-assets.py
Adding a script that will change ignition to gz for all assets that belong to a user.
Large models may fail to upload. I haven't figure out how to solve this. For these models, we'll have to manually upload them via the browser.
I need to add support for worlds.
1. Create a private token via your settings page on app.gazebosim.org.
2. Run the script against yourself (you'll need some models associated with your fuel account).
```
python3 ./gz-update-assets.py -o USERNAME -t PRIVATE_TOKEN
```
> added script to update assets to gz

- Changelog.md
- README.md
- src/ClientConfig.cc
- src/ClientConfig_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- tools/gz-update-assets.py
- tutorials/01_installation.md
- tutorials/04_cpp_api.md
Port gz-fuel-tools9 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools9
> Merge: 9 -> main

- include/gz/fuel_tools/FuelClient.hh
- include/gz/fuel_tools/Helpers.hh
- include/gz/fuel_tools/WorldIdentifier.hh
- src/ClientConfig.cc
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Helpers.cc
- src/Helpers_TEST.cc
- src/LocalCache.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
Fix tests around Windows' handling (or not handling) of `:` and `@` in filesystem paths.
To address this, I did a few things.
1) If a URI has an authority (that is a username or a port in the format `username@host:port`), then we URL encode that to get a "safe" path.
2) Make sure that we are passing `hasAuthority = true` for all of our URIs that use `https`.  This may be a behavior that we want to change in gz-common eventually, but is sufficient for here.
3) Fixes `UniqueName` to generate valid paths for both `ModelIdentifier` and `WorldIdentifier`.  I also choose to make `UniqueName` always return unix-delimited paths, which cleans up some windows-specific test logic.
I believe that this resolves the test failures in `FuelClientTest.CachedWorld` and `FuelClientTest.PatchModelFail` as …
> Re-enabling Windows tests

- src/gz_src_TEST.cc
> Create directories and more output on fail

- include/gz/fuel_tools/FuelClient.hh
- include/gz/fuel_tools/Helpers.hh
- src/CollectionIdentifier_TEST.cc
- src/FuelClient.cc
- src/FuelClient_TEST.cc
- src/Helpers.cc
- src/Helpers_TEST.cc
- src/LocalCache.cc
- src/LocalCache_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/ServerConfig.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
Port `gz-fuel-tools9` to `main`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools9
> Merge gz-fuel-tools9 :arrow_right: main

- .github/workflows/ci.yml
- .github/workflows/triage.yml
- Changelog.md
- src/FuelClient_TEST.cc
- src/gz_src_TEST.cc
Port `gz-fuel-tools8` to `gz-fuel-tools9`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools9...gz-fuel-tools8
> Merge 8 ➡️ 9

- src/LocalCache.cc
Fixes https://github.com/gazebosim/gz-sim/issues/2281
`LocalCache::MatchingModel` and `LocalCache::MatchingWorld` are used to determine if a given Fuel URL is in the local cache. These functions used `LocalCache::AllModels` to get a list of all known models/worlds and compare them to the requested Fuel URL. The problem is that `LocalCache::AllModel` would only look for models/worlds in a predetermined directory, `<cache location>/fuel.gazebosim.org`: https://github.com/gazebosim/gz-fuel-tools/blob/a59c107fd534981c2b1a53d5ba63c77a341b8bc8/src/LocalCache.cc#L232-L235
However, since the argument to `MatchingModel`/`MatchingWorld` would already have the server URL, we shouldn't have to look through `AllModels`. This patch uses the path ` common::joinPaths( …
> Fix `LocalCache` so that models/worlds downloaded via fuel.ignitionrobotics.org can be found in the cache

- src/ClientConfig.cc
This reads the `config.yaml` or `config.yml` file from the cache directory when the ClientConfig is created. Without this change, a user needs to enter the `-c` command line argument each time or manually call the `LoadConfig` function.
1. Create an API key from app.gazebosim.org
2. Create a config.yaml file in `~/.gz/fuel` that contains:
```
---
servers:
-
url: https://fuel.gazebosim.org
private-token: YOUR_API_KEY
```
3. Download a private model with something like `gz fuel download -u https://fuel.gazebosim.org/1.0/OWNER/models/MODEL`.
> Use config.yaml file from default cache location, if it exists

- include/gz/fuel_tools/WorldIdentifier.hh
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
Adds Private functions to WorldIdentifier. This will help facilitate world upload, which is coming in a follow up PR.
Run the WorldIdentifier_TEST unit tet.
> Add Private function to world identifier

- src/RestClient.cc
- src/gz.cc
- src/gz_TEST.cc
The current ASAN build reports quite a few problems related to memory not being freed. I think that I've hunted mos of them if not all. 
Although our Jenkins ASAN builds are not repotring failures from these kind of problems (need to solve https://github.com/gazebosim/gz-cmake/issues/240) they are easy visible from the logs, see the failures for this branch before this PR in: https://build.osrfoundation.org/job/gz_fuel_tools-ci_asan-gz-fuel-tools9-jammy-amd64/31/consoleFull (grep by "LeakSanitizer: detected memory leaks").
If the PR is good and there are no more problems, this testing build should be clean: https://build.osrfoundation.org/job/_test_gz_fuel_tools-ci_asan-gz-fuel-tools9-jammy-amd64/2/consoleFull
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit …
> Clean all ASAN reported memory problems (curl related)

- src/RestClient.cc
The new curl 8.x series deprecate part of the CURL API that is being used in fuel-tools. I was totally new to the CURL APIs but there was a good documentation on how to migrate the old form API to the new MIME API in https://curl.se/libcurl/c/libcurl-tutorial.html (search by Converting from deprecated form api to mime api) so I went ahead and try to get the thing working.
I don't see any new test failure but probably we need someone with more knowledge of fuel to review that things are actually working.
I ran the ASAN analizer but found that we already have problems on the ASAN build (although Jenkins is not reporting them probably because https://github.com/gazebosim/gz-cmake/issues/240). 
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the …
> Migrate curl_formadd from form API to mime API (deprecated in Ubuntu Noble)

- src/gz_TEST.cc
This test shouldn't have the `1.0` in the URL. Not sure how this passed in a previous build.
> Fix a test

- src/gz_TEST.cc
- src/gz_src_TEST.cc
Fixes Fuel_tools4 CI and Fuel_tools7 CI
Reference builds: 
https://build.osrfoundation.org/job/gz_fuel_tools-ci-ign-fuel-tools4-focal-amd64/41/
https://build.osrfoundation.org/job/gz_fuel_tools-ci-ign-fuel-tools7-focal-amd64/48/
I don't think this has been reported, but Citadel and Fortress CI has been failing on Linux to run some tests requiring to download some models. The tests fail with timeouts, but the problem is that the server url is not configured properly, and so it's not capable of downloading anything. 
I fixed this by using the same configuration as in more recent distributions. This will require a Forward Port to Fortress after it gets merged. FYI @Crola1702 
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request …
> Fix tests pulling from wrong server

- src/gz_TEST.cc
- src/gz_src_TEST.cc
Forward port #421 to fix same error on fuel_tools7. FYI @Crola1702 
As the title says
> Fix tests pulling from wrong server (#421)

- include/gz/fuel_tools/CollectionIdentifier.hh
- include/gz/fuel_tools/ModelIdentifier.hh
- include/gz/fuel_tools/WorldIdentifier.hh
- src/CollectionIdentifier.cc
- src/CollectionIdentifier_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
Previously we were relying on UniqueName to hold a Url. UniqueName was updated to generate filesystem-safe paths for both Linux and Windows, so it no longer holds a valid Url.  This adds a peer method to also retrieve the Url of the Model/World/Collection.
> Add Url accessor to Identifiers

- .github/workflows/ci.yml
- README.md
- src/FuelClient_TEST.cc
- src/LocalCache.cc
This also enables codecov and linters.
> Use Ubuntu 24.04 in Github Actions CI workflow

- src/FuelClient.cc
Fix gcc warnings in a few places where GCC was complaining about iterating over values instead of reference.
> Fix GCC warnings

- Changelog.md
- include/gz/fuel_tools/CollectionIdentifier.hh
- include/gz/fuel_tools/ModelIdentifier.hh
- include/gz/fuel_tools/WorldIdentifier.hh
- src/CollectionIdentifier.cc
- src/CollectionIdentifier_TEST.cc
- src/ModelIdentifier.cc
- src/ModelIdentifier_TEST.cc
- src/WorldIdentifier.cc
- src/WorldIdentifier_TEST.cc
Port `gz-fuel-tools9 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools9
> Merge gz-fuel-tools9 ➡️  main

- src/CollectionIdentifier.cc
- src/WorldIdentifier.cc
Fixes clang-tidy warnings related to types used without their header files.
Add missing includes for `gz::common::URI` and `gz::fuel_tools::uriToPath`
> Add missing URI header files

- CMakeLists.txt
- example/CMakeLists.txt
Part of gazebosim/gz-cmake#350.
This increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4.
Check that CI is successful.
> Require cmake 3.22.1

- CMakeLists.txt
- Changelog.md
Preparation for 10.0.0~pre1 release.
Comparison to 9.1.0: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools9_9.1.0...prep_10.0.0pre1
> Prepare for 10.0.0~pre1 release

- tutorials/03_command_line.md
Fixes some minor formatting tutorials running the [command line tutorial](https://gazebosim.org/api/fuel_tools/10/cmdline.html).
> Tutorial tweaks for the command line tutorial.

- tutorials/04_cpp_api.md
Fixes #<NUMBER>
- Add prerequisite : libgflags-dev
- Update code snippets with latest file versions
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: https://github.com/gazebosim/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>
Needed by <PR(s)>
> fix cpp api tutorial

- README.md
Related with this comment https://github.com/gazebosim/gazebo_test_cases/issues/1104#issuecomment-2327151117
> Fixed readme syntax

- CMakeLists.txt
- Changelog.md
Preparation for 10.0.0 release.
Comparison to 10.0.0-pre2: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools10_10.0.0-pre2...gz-fuel-tools10
Needed by <PR(s)>
> Prepare for 10.0.0 Release

- src/cmd/CMakeLists.txt
The cmd file installed on Windows points to a non-existent directory:
LIBRARY_NAME = '../../../lib/gz-fuel_tools10.dll'
Whereas the dll is in bin, not lib.
This PR copies the logic from gz-sim and sdformat.
> Fixed cmd on Windows

- CMakeLists.txt
- Changelog.md
- README.md
- src/cmd/CMakeLists.txt
- tutorials/03_command_line.md
- tutorials/04_cpp_api.md
Port gz-fuel-tools10 to main
Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...gz-fuel-tools10
> Merge 10 -> main

- example/download.cc
- src/gz.cc
Fixed an issue where the download utility returning a success, even if the actual download fails. Main causes appeared to be some seemingly unintended typecasting between `int` and `gz::fuel_tools::Result`, as well as not checking if the result value was actually a success or not.
> Fix return value when download fails

- .github/workflows/ci.yml
- include/gz/fuel_tools/Helpers.hh
- include/gz/fuel_tools/Model.hh
- include/gz/fuel_tools/ModelIdentifier.hh
- include/gz/fuel_tools/WorldIdentifier.hh
Part of https://github.com/gazebo-tooling/release-tools/issues/1222
Jammy isn't officially supported for Ionic, so move linters to use Noble, and enable doxygen checking.
> ci: run cppcheck, cpplint, doxygen on noble

- BUILD.bazel
- test/BUILD.bazel
Use `gz-fuel-tools` name for top level library target instead of `fuel_tools` to be consistent with the module name and also the convention followed in other gz packages (e.g. `gz-common`: https://github.com/gazebosim/gz-common/blob/gz-common6/BUILD.bazel#L66).
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> Use gz-fuel-tools name for top level library target

- CMakeLists.txt
- Changelog.md
Preparation for 11.0.0 release.
Comparison to gz-fuel-tools~pre1: https://github.com/gazebosim/gz-fuel-tools/compare/gz-fuel-tools11_11.0.0-pre1...gz-fuel-tools11
> Prepare for 11.0.0 release
